Models/Venture.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace ExamOne.Models
{
    public class Venture
    {
        [Key]
        public int VentureId {get; set;}

        [Required(ErrorMessage="You must have a Title")]
        [Display(Name="Title: ")]
        public string Title {get; set;}

        [Required(ErrorMessage="Activity Date is required.")]
        [FutureDate]
        public DateTime Date {get; set;}

        [Required(ErrorMessage="Duration is required.")]
        [Range(1,1000, ErrorMessage="Duration has to be a postive amount of time.")]
        public int Duration {get; set;}

        [Required(ErrorMessage="Description is required.")]
        [Display(Name="Description: ")]
        public string Description {get; set;}

        /////////////one to many a venture can only have one planner

        public int UserId {get; set;}
        public List<Rsvp> GuestList {get; set;}
        public User Planner {get; set;}

        public DateTime CreatedAt {get; set;} = DateTime.Now;

        public DateTime UpdatedAt {get; set;} = DateTime.Now;




        ////////////////////////////

        public class FutureDateAttribute : ValidationAttribute
        {
            protected override ValidationResult IsValid(object value, ValidationContext validationContext)
            {
                DateTime check;
                if(value is DateTime)
                {
                    check = (DateTime)value;
    
                    if(check < DateTime.Now)
                    {
                        return new ValidationResult("Activity must be in the future.");
                    }
                    else
                    {
                        return ValidationResult.Success;
                    }
                }
                else
                {
                    return new ValidationResult("Enter a real date.");
                }
            }
        }
    }
}

Controllers/VentureController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using ExamOne.Models;
using Microsoft.AspNetCore.Identity;
using ExamOne.Contexts;
using Microsoft.AspNetCore.Http;
using Microsoft.EntityFrameworkCore;


namespace ExamOne.Controllers
{
    [Route("venture")]
    public class VentureController : Controller
    {
        private HomeContext dbContext;
        public VentureController(HomeContext context)
        {
            dbContext = context; 
        }

        [Route("dashboard")]
        public IActionResult Dashboard()
        {
            User userInDb = LoggedIn();
            if(userInDb == null)
            {
                return RedirectToAction ("LogOut", "Home");
            }
            List<Venture> AllVentures = dbContext.Ventures.Include( v => v.GuestList).ThenInclude( r => r.Guest).Include( v => v.Planner).OrderBy ( v => v.Date).ToList();
            ViewBag.User = userInDb;
            return View(AllVentures);
        }

        ////////////////////////////

        [Route("new/venture")]
        public IActionResult NewVenture()
        {
            User userInDb = LoggedIn();
            if(userInDb == null)
            {
                return RedirectToAction("LogOut", "Home");
            }
            ViewBag.User = userInDb;
            return View();
        }

        ////////////////////////////////////

        [Route("create/venture")]
        public IActionResult CreateVenture(Venture newVent)
        {
            User userInDb = LoggedIn();
            if(userInDb == null)
            {
                return RedirectToAction("LogOut", "Home");
            }
            if(ModelState.IsValid)
            {
                dbContext.Ventures.Add(newVent);
                dbContext.SaveChanges();
                return Redirect($"/venture/{newVent.VentureId}");
            }
            else
            {
                ViewBag.User = userInDb;
                return View("NewVenture");
            }
        }

        //////////////////////////////////


        [HttpGet("{ventureId}")]
        public IActionResult ShowVenture(int ventureId)
        {
            User userInDb = LoggedIn();
            if(userInDb == null)
            {
                return RedirectToAction("LogOut", "Home");
            }
            Venture show = dbContext.Ventures.Include( v => v.Planner).Include ( v => v.GuestList ).ThenInclude( r => r.Guest ).FirstOrDefault( v => v.VentureId == ventureId);
            ViewBag.User = userInDb;
            return View(show);
        }

        //////////////////////////////////

        [HttpGet("delete/{ventureId}")]
        public IActionResult DeleteVenture(int ventureId)
        {
            User userInDb = LoggedIn();
            if(userInDb == null)
            {
                return RedirectToAction("LogOut", "Home");
            }
            Venture remove = dbContext.Ventures.FirstOrDefault( v => v.VentureId == ventureId);
            dbContext.Ventures.Remove(remove);
            dbContext.SaveChanges();
            return RedirectToAction("Dashboard");
        }

        ///////////////////////////////////

        [HttpGet("response/{ventureId}/{userId}/{status}")]
        public IActionResult Rsvp (int ventureId, int userId, string status)
        {
            User userInDb = LoggedIn();
            if(userInDb == null)
            {
                return RedirectToAction("LogOut", "Home");
            }
            if(status == "rsvp")
            {
                Rsvp going = new Rsvp();
                going.UserId = userId;
                going.VentureId = ventureId;
                dbContext.Rsvps.Add(going);
                dbContext.SaveChanges();
            }
            else if(status == "backout")
            {
                Rsvp backout = dbContext.Rsvps.FirstOrDefault( r => r.VentureId == ventureId && r.UserId == userId);
                dbContext.Rsvps.Remove(backout);
                dbContext.SaveChanges();
            }
            else
            {
                return RedirectToAction("Dashboard");
            }
            return RedirectToAction("Dashboard");
        }














        private User LoggedIn()
    {
        User LogIn = dbContext.Users.Include( u => u.PlannedVent).FirstOrDefault(u => u.UserId == HttpContext.Session.GetInt32("UserId"));

        return LogIn;
    }
    }
}

Views/Venture/Dashboard.cshtml
@model List<Venture>


<header>
    <h1>Welcome to the Dojo Activity Center</h1>
    <a asp-action="LogOut" asp-controller="Home">Logout</a>
</header>

<div class="table table-hover">
    <table>
        <thead>
            <tr>
                <th>Activity</th>
                <th>Date and Time</th>
                <th>Duration</th>
                <th>Event Cordinator</th>
                <th># of Participants</th>
                <th>Action</th>
            </tr>
        </thead>
        <tbody>
            @foreach ( var v in @Model)
            {
                <tr>
                    <td><a asp-action="ShowVenture" asp-controller="Venture" asp-route-ventureId="@v.VentureId"> @v.Title</a></td>
                    <td>@v.Date.ToLongDateString() at @v.Date.ToShortTimeString()</td>
                    <td>@v.Duration</td>
                    <td>@v.Planner.FirstName</td>
                    <td>@v.GuestList.Count</td>
                    <td>
                        @if(ViewBag.User.UserId == v.Planner.UserId)
                        {
                            <a asp-action="DeleteVenture" asp-controller="Venture" asp-route-ventureId="@v.VentureId">Delete</a>
                        }
                        else
                        {
                            @if(v.GuestList.All( r => r.UserId != ViewBag.User.UserId))
                            {
                                <a asp-action="Rsvp" asp-controller="Venture" asp-route-ventureId="@v.VentureId" asp-route-userId="@ViewBag.User.UserId" asp-route-status="rsvp">JOIN</a>
                            }
                            @if(v.GuestList.Any( r => r.UserId == ViewBag.User.UserId))
                            {
                                <a asp-action="Rsvp" asp-controller="Venture" asp-route-ventureId="@v.VentureId" asp-route-userId="@ViewBag.User.UserId" asp-route-status="backout">LEAVE</a>
                            }
                        }
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

<a asp-action="NewVenture" asp-controller="Venture" class="btn btn-warning">Add New Activity</a>

Views/Venture/NewVenture.cshtml
@model Venture

<h1>Create an Activity!</h1>
<a asp-controller="Venture" asp-action="Dashboard">HOME</a><br>
<a asp-controller="Home" asp-action="LogOut">LOGOUT</a>

<form class="col-5" asp-action="CreateVenture" asp-controller="Venture" method="post">
    <input type ="hidden" asp-for="UserId" value="@ViewBag.User.UserId">
    <div>
        <span class="red" asp-validation-for="Title"></span>
        <label asp-for="Title"></label>
        <input class="form-control" asp-for="Title">
    </div>
    <div>
        <span class="red" asp-validation-for="Date"></span>
        <label asp-for="Date"></label>
        <input class="form-control" asp-for="Date">
    </div>
    <div>
        <span class="red" asp-validation-for="Duration"></span>
        <label asp-for="Duration"></label>
        <input class="form-control" asp-for="Duration">
        @* <select> *@
            @* <option value="Days">Days</option> *@
            @* <option value="Hours">Hours</option> *@
            @* <option value="Minutes">Minutes</option> *@
        @* </select> *@
    </div>
    <div>
        <span class="red" asp-validation-for="Description"></span>
        <label asp-for="Description"></label>
        <input class="form-control" textarea asp-for="Description" cols="30" rows="5">
    </div>
    <div>
        <input class="btn btn-primary" type="submit">
    </div>
</form>

Views/Venture/ShowVenture.cshtml
@model Venture
@* @model List<Venture> *@

<a asp-controller="Venture" asp-action="Dashboard">HOME</a>
<a asp-controller="Home" asp-action="Logout">LOGOUT</a>

<h1>@Model.Title</h1>

<h2>Event Coordinator: @Model.Planner.FirstName</h2>
<p>Description: @Model.Description</p>

<div>
    <h3>People Attending: </h3>
    <p>
        @foreach ( var r in @Model.GuestList)
        {
            <p> @r.Guest.FirstName</p>
        }
    </p>
</div>





@if(ViewBag.User.UserId == Model.Planner.UserId)
{
    <a asp-action="DeleteVenture" asp-controller="Venture" asp-route-ventureId="@Model.VentureId">Delete</a>
}
else
{
    @if(Model.GuestList.All( r => r.UserId != ViewBag.User.UserId))
    {
        <a asp-action="Rsvp" asp-controller="Venture" asp-route-ventureId="@Model.VentureId" asp-route-userId="@ViewBag.User.UserId" asp-route-status="rsvp">JOIN</a>
    }
    @if(Model.GuestList.Any( r => r.UserId == ViewBag.User.UserId))
    {
        <a asp-action="Rsvp" asp-controller="Venture" asp-route-ventureId="@Model.VentureId" asp-route-userId="@ViewBag.User.UserId" asp-route-status="backout">LEAVE</a>
    }
}






@* <a asp-controller="Venture" asp-action="DeleteVenture">DELETE</a> *@
@* <a asp-controller="Ventrue" asp-action="Rsvp">JOIN</a> *@
@* <a asp-controller="Venture" asp-action="Rsvp">LEAVE</a> *@



@* <table> *@
    @* <thead> *@
        @* <tr> *@
            @* <th>Action</th> *@
        @* </tr> *@
    @* </thead> *@
    @* <tbody> *@
        @* @foreach ( var v in @Model.GuestList) *@
        @* { *@
            @* <tr> *@
                @* <td> *@
                    @* @if(ViewBag.User.UserId == v.Planner.UserId) *@
                    @* { *@
                        @* <a asp-action="DeleteVenture" asp-controller="Venture" asp-route-ventureId="@v.VentureId">Delete</a> *@
                    @* } *@
                    @* else *@
                    @* { *@
                        @* @if(v.GuestList.All( r => r.UserId != ViewBag.User.UserId)) *@
                        @* { *@
                            @* <a asp-action="Rsvp" asp-controller="Venture" asp-route-ventureId="@v.VentureId" asp-route-userId="@ViewBag.User.UserId" asp-route-status="rsvp">JOIN</a> *@
                        @* } *@
                        @* @if(v.GuestList.Any( r=> r.UserId == ViewBag.User.UserId)) *@
                        @* { *@
                            @* <a asp-action="Rsvp" asp-controller="Venture" asp-route-ventureId="@v.VentureId" asp-route-userId="@ViewBag.User.Userid" asp-route-status="rsvp">LEAVE</a> *@
                        @* } *@
                    @* } *@
                @* </td> *@
            @* </tr> *@
        @* } *@
    @* </tbody> *@
@* </table> *@